### ISSUE TITLE
intraprocess communication

### ISSUE THREAD

**Issue by alessioprini** [fmrico/cascade_lifecycle#1]
Hi and thanks for this package.

I these days I'm trying to use it on a project constituted by composable (lifecycle) node using intraprocess communication.
Trying to launch it I get this error:

> [control_container]: Component constructor threw an exception: intraprocess communication is not allowed with keep all history qos policy

In your opinion is it possible to change this part https://github.com/fmrico/cascade_lifecycle/blob/dc1b8dc50573570b83ac91f4430440e50d492a04/rclcpp_cascade_lifecycle/src/rclcpp_cascade_lifecycle/rclcpp_cascade_lifecycle.cpp#L49-L64

checking if the intraprocess communication is it used or not with a simple:

    if(options.use_intra_process_comms())
    {
         activations_pub_ = create_publisher<cascade_lifecycle_msgs::msg::Activation>(
	     "/cascade_lifecycle_activations",
	     rclcpp::QoS(1000));
         ...
    }
    else
    {
         activations_pub_ = create_publisher<cascade_lifecycle_msgs::msg::Activation>(
	    "/cascade_lifecycle_activations",
	    rclcpp::QoS(1000).keep_all().transient_local().reliable());
        ...
    }

or do you see some drawback ?

Thanks in advance
Alessio

**Comment by fmrico** [comment]
Hi @alessioprini 

I have just merged #2 , and it changes this part. The QoS is the one you request.

Best
