### ISSUE TITLE
Support for rclpy -> LifecycleNode

### ISSUE THREAD

**Issue by v-snap** [fmrico/cascade_lifecycle#9]
is it possible to trigger rclpy->Lifecyclenode (node 'A' ) from cascade->Lifecyclenode (node 'B' ) ?

**Comment by fmrico** [comment]
@Juancams has a Python versión that he probably would like to PR ;P

https://github.com/Juancams/cascade_lifecycle

**Comment by fmrico** [comment]
Solved in #10
